import "@/style/globals.css";
import type { Metadata } from "next";
import type { LayoutParams } from "@/types";
import React from "react";
import { cookies } from "next/headers";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const languages = ["it", "en"];

// export async function generateStaticParams() {
//   return languages.map((language) => {
//     language;
//   });
// }
export default function RootLayout({
  children,
}: // params: { locale },
LayoutParams) {
  let cookie;
  if (cookies().has("locale")) {
    cookie = cookies().get("locale");
    console.log("cookie", cookie);
  }
  let locale = cookie ? cookie.value : "it";
  console.log("LAYOUT LOCALE", locale);

  return (
    <html lang={locale}>
      <body>
        <LanguageSwitcher currentLocale={locale} />
        {/* {React.cloneElement(children as any, {
          locale: "CIAO",
        })} */}
        <div className="p-4"> {children}</div>
      </body>
    </html>
  );
}
