import React from "react";
import { cookies } from "next/headers";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { draftMode } from "next/headers";

import { LanguageSwitcher } from "@/components/LanguageSwitcher";
import { LayoutQueryDocument } from "@/graphql/generated";
import type { LayoutParams } from "@/types";

import "@/style/globals.css";
import queryDatoCMS from "@/lib/fetchDato";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: // params: { locale },
LayoutParams) {
  let cookie;
  if (cookies().has("locale")) {
    cookie = cookies().get("locale");
    console.log("cookie", cookie);
  }
  let locale = cookie ? cookie.value : "it";
  console.log("LAYOUT LOCALE", locale);
  const { isEnabled } = draftMode();
  const data = await queryDatoCMS(LayoutQueryDocument, {}, isEnabled);

  if (!data.site) notFound();

  return (
    <html lang={locale}>
      <body>
        <LanguageSwitcher currentLocale={locale} />
        <div>
          <pre>{JSON.stringify(data.menu)}</pre>
        </div>
        <div className="p-4"> {children}</div>
      </body>
    </html>
  );
}
